### ISSUE TITLE
When using a higher version(26.0.0) of Docker, aconcli generates an FS layer with a size of 0

### ISSUE THREAD

**Issue by yanxue-intel** [intel/ACON#103]
**[tdx@localhost quote]$ make**
openssl ecparam -genkey -name secp384r1 -out signer.pem
openssl req -x509 -sha384 -key signer.pem -out signer.cer -outform der -subj /CN=self-signed-signer.pem
aconcli init
Initialized empty ACON repository in .acon
docker build -t sampleserver -f server/Dockerfile  /home/tdx/ACON/samples/quote/../..
[+] Building 2.8s (11/11) FINISHED                                                                                  docker:default
=> [internal] load build definition from Dockerfile                                                                          0.0s
=> => transferring dockerfile: 535B                                                                                          0.0s
=> [internal] load metadata for docker.io/library/alpine:latest                                                              2.6s
=> [internal] load .dockerignore                                                                                             0.0s
=> => transferring context: 2B                                                                                               0.0s
=> [builder 1/5] FROM docker.io/library/alpine:latest@sha256:c5b1261d6d3e43071626931fc004f70149baeba2c8ec672bd4f27761f8e1ad  0.0s
=> [internal] load build context                                                                                             0.0s
=> => transferring context: 357B                                                                                             0.0s
=> CACHED [builder 2/5] RUN 
apk update && apk add g++ libc++-static               0.0s
=> CACHED [builder 3/5] WORKDIR /work                                                                                        0.0s
=> CACHED [builder 4/5] COPY sdk/ samples/quote/server/ ./                                                                   0.0s
=> CACHED [builder 5/5] RUN c++ -std=c++14 -Os -static-pie -flto -Iinclude/ -Wl,--gc-sections,-s src/*.cpp -o quote_server   0.0s
=> CACHED [stage-1 1/1] COPY --from=builder /work/quote_server /                                                             0.0s
=> exporting to image                                                                                                        0.0s
=> => exporting layers                                                                                                       0.0s
=> => writing image sha256:6b45e840f5cd5169b6ebed7ce7f5f791dd032b717d43ec57b59d2498828dfd24                                  0.0s
=> => naming to docker.io/library/sampleserver                                                                               0.0s
aconcli generate -i sampleserver server.json
aconcli sign -k signer.pem -c signer.cer server.json
CGO_ENABLED=0 go -C client build -v

**[tdx@localhost quote]$ ll .acon/blobs/sha384/**
total 0
-rw------- 1 tdx tdx 0 Apr  2 16:33 38b060a751ac96384cd9327eb1b1e36a21fdb71114be07434c0cc7bf63f6e1da274edebfe76f65fbd51ad2f14898b95b.tar

**Comment by xxu36** [comment]
Fixed on main branch
