### ISSUE TITLE
[OpenID test] `aconcli invoke` has no output

### ISSUE THREAD

**Issue by billionairiam** [intel/ACON#113]
```
[sgx@sgx-emr02 test]$ ./aconcli invoke -c :5532 -e 2 CheckUid
2024/06/20 09:58:53 Service: Connecting :5532


```
Which works normally in `--nologin` mode.

**Comment by xiangquanliu** [comment]
The root cause of no output  - use the non-production acond.
However, there is another  bug of copying stdin buffer the child process, I'd like to use this link to track it.

**Comment by xiangquanliu** [comment]
@billionairiam, fix has been in the branch.
