### ISSUE TITLE
[scripts] `start_rust_buildenv` can't work in GitHub actions

### ISSUE THREAD

**Issue by billionairiam** [intel/ACON#28]
1. `start_rust_buildenv` use 
```
docker run $RM -it --name $cname --label ACON=$ACON -v $ACON:/acon -w /acon/acond \
                -e HTTPS_PROXY -e https_proxy ${U:+-e U=${U/#.*/$(id -u):$(id -g)}} $rustimg sh -c "
                . /etc/os-release || {
                    echo -e \"${_err}/etc/os-release: Not found\" >&2
                    exit 1
                }
```
to start a container which will cause [Error "The input device is not a TTY"](https://stackoverflow.com/questions/43099116/error-the-input-device-is-not-a-tty).
So I suggest use `docker run $RM -i` instead.
2. When the action starts, it will delete the repo and redownload it. but it doesn't have enough permission to delete the folder of `scripts/deps`.

**Comment by binxing** [comment]
@billionairiam, I just submitted a PR to fix the TTY problem. Please review.

Regarding the 2nd problem, I'm still working on it and will push to the same PR once I have a solution.
