### ISSUE TITLE
[`aconcli`] Build error

### ISSUE THREAD

**Issue by billionairiam** [intel/ACON#33]
When I run `go generate && go build `
It will report
```
# aconcli/service
service/service.go:160:13: r.GetReport undefined (type *__.ReportResponse has no field or method GetReport)
```
And I didn't find `GetReport` function in `struct ReportResponse` , Maybe the interface changed.

**Comment by xxu36** [comment]
@billionairiam Yes, the proto file in `acond` has been updated. `aconcli` code will sync with it.

**Comment by binxing** [comment]
@billionairiam has fixed this issue so close it now.
