### ISSUE TITLE
Unexpected errors while running `make clean` under samples/quote.

### ISSUE THREAD

**Issue by xiangquanliu** [intel/ACON#82]
Steps to reproduce:
1. Go to directory under samples/quote.
2. Run `make clean` and will get error like below.
docker rmi -f sampleserver
Error response from daemon: No such image: sampleserver:latest

Expected:
Not let users to see errors like this?

**Comment by binxing** [comment]
`docker` continues to return "success" even when the docker image to delete is not found. So we don't fix this issue.
