### ISSUE TITLE
[sample/quote] Need to modify writableFS's value to 'true' in server.json

### ISSUE THREAD

**Issue by yanxue-intel** [intel/ACON#91]
Default writableFS value is 'false' in sample/quote's manifest, which caused failure of running workload.

**Comment by xiangquanliu** [comment]
I just tested with the latest source codes and found it works well. @binxing @yanxue-intel 
1) Initrd built by myself
2) Image built by Xiaofeng
I can't run `make` successfully under samples/quote/ and suspect it is an build environment issue.

**Comment by xiangquanliu** [comment]
Attached the manifest:
{
    "aconSpecVersion": [
        1,
        0
    ],
    "layers": [
        "sha384/634b27f7651fae2d50b6545ff000a82800aa8bfefff5974edefeddf43d4b3c85b8296c6660ee0999c3a0f4426492b1d9"
    ],
    "aliases": {},
    "entrypoint": [
        "/quote_server"
    ],
    "env": [
        "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    ],
    "workingDir": "/",
    "uids": [],
    "logFDs": [],
    "writableFS": false,
    "noRestart": false,
    "signals": [],
    "maxInstances": 1,
    "policy": {
        "rejectUnaccepted": false
    }
}

**Comment by binxing** [comment]
@yanxue-intel please put in the kernel versions and their behaviors with regard to this issue, and nail the "best" kernel version.

**Comment by andyzyb** [comment]
Is Acond using TDVMCall or vsock for communicating with QGS?

**Comment by xiangquanliu** [comment]
> Is Acond using TDVMCall or vsock for communicating with QGS?

Currently we're using TCVMCALL.
